### ISSUE TITLE
 inconsistencies with the AAR which is not updated

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/speech-android-sdk#4]
I got an email with useful feedback regarding the discrepancy between our README and the classes that we provide in the sdk.

> In instantiating the `SpeechToText` instance, the README uses `new SpeechConfiguration()`.  This is also what the example application does.  However, the AAR does not contain the `SpeechConfiguration` class.  The method signature implied by the README is `initWithContext(URI, Context, SpeechConfiguration)`.  
> 
> The method signature in the AAR is `initWithContext(URI, Context, boolean)`.  The boolean here represents `isUsingVad` but the documentation makes no mention of what "Vad" is, how it should be used, etc.
> 
> This is one of the inconsistencies I've found in the SDK.  The very next step in the README is `setCredentials(username, password)` - but in the AAR does not contain this method.  Is it instead broken out to two methods, one for user and one for password.
> 
> It goes on and on like this (`ISpeechDelegate` vs `SpeechDelegate`, `setModel(String)` which does not exist at all in the AAR, etc.).

**Comment by shenybluemix** [comment]
I am using AAR as the SDK for speech to text on Android because from the README it looks it makes Audio capture and encoding to the format which Watson support on Android much easier.  

However, there are huge inconsistent of this AAR file and what is described in README. 

Shall we use this SDK for speech to text service or the JAVA SDK - https://github.com/watson-developer-cloud/java-sdk ?

@germanattanasio

**Comment by daniel-bolanos** [comment]
Hello @shenybluemix , sorry for the incovenience, the AAR is outdated. Can you please regenerate it from the code and make a pull request? thank you

**Comment by germanattanasio** [comment]
The aar file was updated
